# Numpy Introduction

In [2]:
# pip install Numpy

In [3]:
import numpy as np

# What is an array?

- An array is a data structure that stores a collection of elements of the same data type in a single variable. Each element is identified by an index or key, which allows you to access and manipulate the elements individually.
- In Python, an array is a collection of elements of the same data type, similar to a list. However, arrays in Python are typically implemented using the numpy library, which provides a more efficient and optimized data structure for numerical computations.

### Example Code

In [4]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [5]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [6]:
#a2 = a[:, np.newaxis]
#print(a2)
#a2.shape

In [7]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

# Why do we have 1D, 2D and 3D arrays and where do we need them in data science?

### 1D Arrays (Vectors)
A 1D array, also known as a vector, is a sequence of elements that can be accessed using a single index. It's like a list of numbers.

Example Use Cases:

- Storing a list of values, such as temperatures or stock prices, over time.
- Representing a single feature or column in a dataset.

### 2D Arrays (Matrices)
A 2D array, also known as a matrix, is a table of elements that can be accessed using two indices (row and column). It's like a spreadsheet.

Example Use Cases:

- Representing a dataset with multiple features (columns) and samples (rows).
- Performing matrix operations, such as linear algebra or image processing.

### 3D Arrays (Tensors)
A 3D array, also known as a tensor, is a cube of elements that can be accessed using three indices (row, column, and depth). It's like a stack of matrices.

Example Use Cases:

- Representing a dataset with multiple features (columns), samples (rows), and time steps (depth).
- Performing 3D image processing or computer vision tasks.

# Creating arrays with Numpy

In [8]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3,4,5,6), (5,6,7,8,9,10)])

In [9]:
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [10]:
print(b)
b.shape

[[ 1  2  3  4  5  6]
 [ 5  6  7  8  9 10]]


(2, 6)

In [15]:
b.dtype

dtype('int32')

## Initialize Arrays

In [11]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
zeros.dtype

dtype('float64')

In [13]:
#Identity Matrix
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Attributes

In [22]:
a.size # Gives us number of elements inside an array

6

In [20]:
len(a) # Gives us length of array

6

In [21]:
a.ndim # Gives us the dimension of array

1

In [24]:
a.shape # Gives us shape of array

(6,)

# Basic Operations

In [25]:
a

array([1, 2, 3, 4, 5, 6])

In [26]:
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  9, 10]])

In [28]:
c = a - b #subtraction
c

array([[ 0,  0,  0,  0,  0,  0],
       [-4, -4, -4, -4, -4, -4]])

In [30]:
h = a + b #addition
h

array([[ 2,  4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14, 16]])

In [33]:
#Another method for addition in arrays
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14, 16]])

In [34]:
m = a * b #multiplication
m

array([[ 1,  4,  9, 16, 25, 36],
       [ 5, 12, 21, 32, 45, 60]])

In [36]:
d = a / b #division
d

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556,
        0.6       ]])

In [39]:
#Square of each element
k = a**2
k

array([ 1,  4,  9, 16, 25, 36])