# Numpy (Part-2)

In [114]:
import numpy as np

In [115]:
#Empty Array
empty = np.empty((2,3))
empty

array([[9.48706702e+170, 1.04870818e+242, 2.27825781e-076],
       [2.13851148e-081, 7.42982704e+015, 3.99762988e-315]])

In [116]:
empty = np.empty((2,3))
print(empty)
print("___________________________________________________")
print(empty[0])

[[9.48706702e+170 1.04870818e+242 2.27825781e-076]
 [2.13851148e-081 7.42982704e+015 3.99762988e-315]]
___________________________________________________
[9.48706702e+170 1.04870818e+242 2.27825781e-076]


In [117]:
#Arange function
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
#Reshape
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
#Even number
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [120]:
#Odd Numbers
odd = np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [121]:
#Specific difference between numbers
diff = np.arange(0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [122]:
#linspace function
lin = np.linspace(0,10,num=5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [123]:
lin = np.linspace(0,-10,num=5)
lin

array([  0. ,  -2.5,  -5. ,  -7.5, -10. ])

In [124]:
#Define the data type of array
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [125]:
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

# What is the difference between int32 & 64?

**int32:**
- A 32-bit signed integer type
- Occupies 4 bytes (32 bits) of memory
- Range: -2,147,483,648 to 2,147,483,647

**int64**
- A 64-bit signed integer type
- Occupies 8 bytes (64 bits) of memory
- Range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807

### Key differences:

- Size: int64 is twice as large as int32, occupying 8 bytes of memory compared to 4 bytes.
- Range: int64 has a much larger range than int32, making it suitable for representing very large or very small integers.

In [126]:
#Sorting
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [127]:
#Concatenation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [128]:
#Concatenation on specific axis
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [129]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [130]:
#Create a 3D array
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [131]:
a.ndim

3

In [132]:
a.size

8

In [133]:
len(a)

2

In [134]:
a.dtype

dtype('int32')

In [135]:
a.shape

(2, 2, 2)

In [136]:
a.reshape(4,1,2)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]],

       [[7, 8]]])

In [137]:
#array conversion
#Create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [138]:
#Convert into 2D Array
b = a[np.newaxis, :]
b.shape
b

array([[1, 2, 3, 4, 5, 6, 7]])

In [139]:
c = a[:, np.newaxis]
c.shape
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

# Indexing and slicing

In [140]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [141]:
a[1:7]

array([2, 3, 4, 5, 6, 7])

In [142]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [143]:
b[b > 11]

array([12])

In [144]:
#Filter even numbers
b[b % 2 == 0] 

array([ 2,  4,  6,  8, 10, 12])

In [145]:
 #Filter odd numbers
b[b % 2 == 1] 

array([ 1,  3,  5,  7,  9, 11])

In [146]:
#Use two conditions
b[(b > 2) & (b % 2 == 0)]

array([ 4,  6,  8, 10, 12])

In [147]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [148]:
#Creating an array from a dataset
array1 = np.arange(0,50,5)
array1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [149]:
a = array1[3:9]
a

array([15, 20, 25, 30, 35, 40])

In [150]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [151]:
c = np.vstack(b)
c

array([[ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

# Matrices

In [152]:
#Creating a 2x3 matrix
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
#Create a matrix of big dimension
b = np.arange(0, 100, 1).reshape(10,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [154]:
#Slicing a matrix
b[0:3, 4:7]

array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26]])

### Operations

In [155]:
b.max()

99

In [156]:
b.min()

0

In [157]:
b.sum()

4950

In [158]:
b.mean()

49.5

In [159]:
b.min(axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [161]:
m + np.array([10,20])

array([[10, 22],
       [14, 26],
       [18, 30],
       [22, 34],
       [26, 38]])

In [162]:
np.vstack((m, np.array([12,24])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [12, 24]])

In [163]:
#Reverse array
np.flip(b)

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

(array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10], dtype=int64),
 array([ 0. ,  9.9, 19.8, 29.7, 39.6, 49.5, 59.4, 69.3, 79.2, 89.1, 99. ]))

In [164]:
# Import necessary libraries
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Load the dataset
X = np.array([[2.5, 5.1], [3.2, 6.2], [4.0, 7.0], [4.5, 8.3], [5.1, 9.2]])
y = np.array([10.2, 12.4, 14.5, 16.3, 18.1])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared Score:", r2)

Mean Squared Error: 0.005744179989183055
R-squared Score: nan


c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_regression.py:1187: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
